name: chatbot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  chat_bubbles: ^1.7.0
  cookie_jar: ^4.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  firebase_auth: ^5.5.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  firebase_core: ^3.12.1
  cloud_firestore: 5.6.5
  animated_text_kit: ^4.2.3
  cached_network_image: ^3.4.1
  just_audio: ^0.9.18  
  audioplayers: ^6.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Group.png
    - assets/images/logo.png
    - assets/images/Frame.png
    - assets/images/
    - assets/songs/
    - assets/songs/blinding_lights.mp3