// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qD-VUVNC38UmJiP6jfjqAsExrN9pNTQ',
    appId: '1:411705345064:web:3e128f947ed202bb18e11d',
    messagingSenderId: '411705345064',
    projectId: 'akash-7094f',
    authDomain: 'akash-7094f.firebaseapp.com',
    databaseURL: 'https://akash-7094f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'akash-7094f.firebasestorage.app',
    measurementId: 'G-5SN34V1DFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcu0-Jl-kyJZ5NOzHHibkwvgtFRJKQrw',
    appId: '1:411705345064:android:1d660ed78a669b0818e11d',
    messagingSenderId: '411705345064',
    projectId: 'akash-7094f',
    databaseURL: 'https://akash-7094f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'akash-7094f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Elk8VQT8YmOvGPM68TyQAIAdFudISIQ',
    appId: '1:411705345064:ios:c1f724d18ff866eb18e11d',
    messagingSenderId: '411705345064',
    projectId: 'akash-7094f',
    databaseURL: 'https://akash-7094f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'akash-7094f.firebasestorage.app',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Elk8VQT8YmOvGPM68TyQAIAdFudISIQ',
    appId: '1:411705345064:ios:c1f724d18ff866eb18e11d',
    messagingSenderId: '411705345064',
    projectId: 'akash-7094f',
    databaseURL: 'https://akash-7094f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'akash-7094f.firebasestorage.app',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2qD-VUVNC38UmJiP6jfjqAsExrN9pNTQ',
    appId: '1:411705345064:web:3e128f947ed202bb18e11d',
    messagingSenderId: '411705345064',
    projectId: 'akash-7094f',
    authDomain: 'akash-7094f.firebaseapp.com',
    databaseURL: 'https://akash-7094f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'akash-7094f.firebasestorage.app',
    measurementId: 'G-5SN34V1DFB',
  );

}